from __future__ import annotations

PROJECT_COLUMNS: tuple[str, ...] = (
    "key",
    "project_name",
    "project_type",
    "promoter_name",
    "project_registration_no",
    "status_of_the_project",
    "acknowledgement_no",
    "project_pin_code",
    "project_city",
    "project_state",
    "project_location_raw",
    "promoter_address_raw",
    "promoter_contact_details",
    "submitted_date",
    "last_modified",
    "estimated_commencement_date",
    "actual_commencement_date",
    "estimated_finish_date",
    "actual_finish_date",
    "approved_on_date",
    "past_experience_of_promoter",
    "bank_details",
    "land_area",
    "construction_area",
    "total_floor_area_under_commercial_or_other_uses",
    "total_floor_area_under_residential",
    "project_cost_detail",
    "number_of_residential_units",
    "number_of_commercial_units",
    "building_details",
    "complaints_litigation_details",
    "uploaded_documents",
    "authorised_signatory_details",
    "co_promoter_details",
    "project_description",
    "provided_faciltiy",
    "professional_information",
    "development_agreement_detail",
    "construction_progress",
    "land_detail",
    "document_urls",
    "members_details",
    "retrieved_on",
    "config_id",
    "data",
    "promoters_details",
    "domain",
    "state",
    "crawl_machine_ip",
    "machine_name",
    "is_updated",
    "is_duplicate",
    "url",
    "last_updated",
    "updated_fields",
    "project_images",
    "detail_images",
    "lister_images",
    "images",
    "old_updates",
    "status_update",
    "iw_part_processed",
    "iw_processed",
    "last_crawled_date",
    "land_area_details",
    "doc_ocr_url",
    "proposed_timeline",
    "checked_updates",
    "checked_updates_date",
    "rera_housing_found",
    "is_live",
    "alternative_rera_ids",
)

PROJECT_COLUMN_SET = set(PROJECT_COLUMNS)

REQUIRED_PROJECT_FIELDS = {
    "key",
    "project_name",
    "project_registration_no",
    "url",
    "state",
    "domain",
}

TEXT_FIELDS = {
    "key",
    "project_name",
    "project_type",
    "promoter_name",
    "project_registration_no",
    "status_of_the_project",
    "acknowledgement_no",
    "project_pin_code",
    "project_city",
    "project_state",
    "project_description",
    "domain",
    "state",
    "crawl_machine_ip",
    "machine_name",
    "url",
    "images",
}

JSONB_FIELDS = {
    "project_location_raw",
    "promoter_address_raw",
    "promoter_contact_details",
    "bank_details",
    "project_cost_detail",
    "building_details",
    "complaints_litigation_details",
    "uploaded_documents",
    "authorised_signatory_details",
    "co_promoter_details",
    "provided_faciltiy",
    "professional_information",
    "development_agreement_detail",
    "construction_progress",
    "land_detail",
    "document_urls",
    "members_details",
    "data",
    "promoters_details",
    "old_updates",
    "status_update",
    "land_area_details",
    "proposed_timeline",
}

DATETIME_FIELDS = {
    "submitted_date",
    "last_modified",
    "estimated_commencement_date",
    "actual_commencement_date",
    "estimated_finish_date",
    "actual_finish_date",
    "approved_on_date",
    "retrieved_on",
    "last_updated",
    "last_crawled_date",
    "checked_updates_date",
}

INTEGER_FIELDS = {
    "past_experience_of_promoter",
    "number_of_residential_units",
    "number_of_commercial_units",
    "config_id",
}

FLOAT_FIELDS = {
    "land_area",
    "construction_area",
    "total_floor_area_under_commercial_or_other_uses",
    "total_floor_area_under_residential",
}

BOOLEAN_FIELDS = {
    "is_updated",
    "is_duplicate",
    "iw_part_processed",
    "iw_processed",
    "checked_updates",
    "rera_housing_found",
    "is_live",
}

ARRAY_FIELDS = {
    "updated_fields",
    "project_images",
    "detail_images",
    "lister_images",
    "doc_ocr_url",
    "alternative_rera_ids",
}

DB_MANAGED_FIELDS = {
    "is_updated",
    "retrieved_on",
    "last_updated",
    "last_crawled_date",
    "updated_fields",
    "old_updates",
}

UPDATE_IGNORED_FIELDS = {
    "retrieved_on",
    "last_crawled_date",
    "is_updated",
    "last_updated",
    "updated_fields",
    "old_updates",
}
